gauss3_6_qnn_src = [
    meson.current_source_dir() / 'quick_dot_ai_qnn.cpp',
    meson.current_source_dir() / 'gauss3_6_qnn.cpp',
    meson.current_source_dir() / 'gauss3_8_qnn.cpp',
    meson.current_source_dir() / 'generate_qnn_utils.cpp',
    meson.current_source_dir() / 'android_memory_allocator.cpp',
]

gauss3_6_qnn_inc = include_directories('.')

quick_dot_ai_src += gauss3_6_qnn_src
quick_dot_ai_inc += gauss3_6_qnn_inc
